version: "3"

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:16.2-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: always
    ports:
      - "8025:8025"
      - "${MAILER_PORT}:1025"