version: "3"

volumes:
  prometheus_data:
  grafana_data:

networks:
  grafana:

services:
  loki:
    image: grafana/loki:2.9.2
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana

  promtail:
    image: grafana/promtail:2.9.2
    restart: always
    volumes:
      - ../logs:/eventflow/logs
      - ./promtail/config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    ports:
      - "9080:9080"
    networks:
      - grafana

  grafana:
    image: grafana/grafana:11.2.2
    restart: always
    ports:
      - "6000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          basicAuth: false
          orgId: 1
          url: http://host.docker.internal:3100
          isDefault: false
          version: 1
          editable: true
        - name: Prometheus
          type: prometheus
          access: proxy 
          basicAuth: false
          orgId: 1
          url: http://host.docker.internal:9090
          isDefault: false
          version: 1
          editable: true
        EOF
        /run.sh

  prometheus:
    image: prom/prometheus:v2.37.9
    networks:
      - grafana
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yml
      - prometheus_data:/prometheus

